[package]
name = "ip-cli"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.43"
clap = "2.33.3"
ipdb = "0.1.4"
cli-table = "0.4.6"
lazy_static = "1.4.0"

[profile.release]
lto = true
opt-level = "z"
panic = "abort"
